---
- name: Rolling update on Kubernetes deployment 
  hosts: localhost
  gather_facts: no
  tasks:
  
    - name: Set image version from environment variable in workflows 
      set_fact:
        new_version: "{{ new_version }}" 

    - name: Check if image exists
      command: "docker pull ghcr.io/enkas1/devops3_examinering:{{ new_version }}"
      register: pull_image
      ignore_errors: yes
      failed_when: pull_image.rc != 0
      changed_when: false

    - name: Fail if image does not exist
      fail:
        msg: "Docker image ghcr.io/enkas1/devops3_examinering:{{ new_version }} not found!"
      when: pull_image.rc != 0

    - name: Update image
      command: |
        kubectl set image deployment/frontend nginx-frontend=ghcr.io/enkas1/devops3_examinering:{{ new_version }}
      register: update_result
      failed_when: update_result.rc != 0

    - name: Wait for rollout to complete 
      block:
        - name: Polling rollout status
          command: kubectl rollout status deployment/frontend
          register: rollout_status
          retries: 5  
          delay: 10  
          until: rollout_status.rc == 0
          failed_when: rollout_status.rc != 0
          changed_when: false

    - name: Rollback if deployment fails
      command: |
        kubectl rollout undo deployment/frontend
      when: rollout_status.rc != 0
      notify:
        - Notify rollback

  handlers:
    - name: Notify rollback
      debug:
        msg: "Rolling update failed. Rolled back to the previous stable version."
